django/kream/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "common"

urlpatterns = [
    path("register/", views.register, name="register"),
    # login 처리를 하는 뷰가 함수형뷰가 아니라 클래스뷰임
    # 클래스뷰를 함수형처럼 사용하려면 as_view() 사용
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="common/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # 기존 비밀번호 변경 후 세션 값 다시 담아줌
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="common/password_change.html",
            success_url=reverse_lazy("index"),
        ),
        name="password_change",
    ),
    # 비밀번호 초기화
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="common/password_reset.html",
            email_template_name="common/password_reset_email.txt",
            success_url=reverse_lazy("common:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html",
            success_url=reverse_lazy("common:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="common/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

django/kream/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("kream/", include("kream.urls")),
    path("", RedirectView.as_view(url="/common/login/"), name="index"),
    path("common/", include("common.urls")),
]

django/kream/kream/urls.py
from django.urls import path
from . import views


app_name = "kream"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("detail/<int:pid>/<int:year>/", views.detail, name="detail"),
    path("list/", views.list, name="list"),
    path("monthList/", views.monthList, name="monthList"),
    path("monthly/<int:year>/<int:month>/", views.monthlyReport, name="monthlyReport"),
    path("checkList/", views.checkList, name="checkList"),
    path("checkListDetail/<int:cid>/", views.checkListDetail, name="checkListDetail"),
    path("checkListDetail/modify/<int:cid>/", views.modify, name="modify"),
    path("checkListDetail/delete/<int:cid>/", views.delete, name="delete"),
    path("checkListCreate/", views.create, name="create"),
    path("sizeReport/<int:pid>/", views.sizeReport, name="sizeReport"),
    path("predictSales/<int:pid>/", views.predictSales, name="predictSales"),
]

django/kream/kream/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    brand = models.CharField(max_length=30)
    name_kor = models.CharField(max_length=30)
    name_eng = models.CharField(max_length=30)
    model_no = models.CharField(max_length=20)
    release_date = models.CharField(max_length=20)
    color = models.CharField(max_length=10)
    original_price = models.IntegerField(default=0)
    img_url = models.CharField(max_length=200)
    product_detail_url = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name_kor


class Trade_Total(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    trade_size = models.CharField(max_length=10)
    trade_price = models.IntegerField(default=0)
    trade_year = models.IntegerField(default=0)
    trade_month = models.IntegerField(default=0)
    trade_hour = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.product.name_kor


class Check_List(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default="default_title")
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title

django/kream/kream/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Product, Trade_Total, Check_List
from django.db.models import Sum, Case, When, IntegerField, Count, Max, Avg, Min
from collections import Counter
from io import BytesIO
from django.core.paginator import Paginator
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import base64
import pandas as pd
import numpy as np
import matplotlib
from sklearn.linear_model import LinearRegression


matplotlib.use("Agg")


# Create your views here.
@login_required(login_url="common:login")
def detail(request, pid, year):
    single_product = get_object_or_404(Product, id=pid)
    product_list = Product.objects.all()

    # 전체 판매금액과 평균금액은 동일
    # trade = Trade.objects.filter(product=single_product, trade_year=year)[0]

    total_sum = Trade_Total.objects.values("product").annotate(
        total_sales=Sum("trade_price")
    )
    # <QuerySet [{'product': 1, 'total_sales': 663678}, {'product': 2, 'total_sales': 718412}, {'product': 3, 'total_sales': 9341}]>

    total_sum_data = [
        data["total_sales"] for data in total_sum if data["product"] == pid
    ]

    filtered_total_sum_data = 0
    filtered_total_avg_data = 0

    if total_sum_data:
        filtered_total_sum_data = total_sum_data[0]
    else:
        total_sum_data = 0

    total_avg = Trade_Total.objects.values("product").annotate(
        avg_sales=Avg("trade_price")
    )
    # <QuerySet [{'product': 1, 'total_sales': 663678}, {'product': 2, 'total_sales': 718412}, {'product': 3, 'total_sales': 9341}]>

    total_avg_data = [data["avg_sales"] for data in total_avg if data["product"] == pid]

    if total_avg_data:
        filtered_total_avg_data = total_avg_data[0]
    else:
        total_avg_data = 0

    # ===============================================================================

    total_sum_year = Trade_Total.objects.values("product", "trade_year").annotate(
        total_sales=Sum("trade_price")
    )

    total_sum_data_curr_year = [
        data["total_sales"]
        for data in total_sum_year
        if data["trade_year"] == year and data["product"] == pid
    ]

    total_sum_data_prev_year = [
        data["total_sales"]
        for data in total_sum_year
        if data["trade_year"] == year - 1 and data["product"] == pid
    ]

    if total_sum_data_curr_year:
        total_sum_data_curr_year = total_sum_data_curr_year[0]
    else:
        total_sum_data_curr_year = 0

    if total_sum_data_prev_year:
        total_sum_data_prev_year = total_sum_data_prev_year[0]
    else:
        total_sum_data_prev_year = 0

    # =====================================================================
    # 년도 선택 항목들
    year_list = Trade_Total.objects.values("product", "trade_year").order_by(
        "-trade_year"
    )
    year_list_data = [data for data in year_list if data["product"] == pid]
    year_list_data = sorted(
        set(data["trade_year"] for data in year_list_data), reverse=True
    )

    # =========================================================================
    # 선그래프 월데이터
    month_list = (
        Trade_Total.objects.values("product", "trade_year", "trade_month")
        .annotate(total_sales=Sum("trade_price"))
        .order_by("trade_month")
    )

    month_list_data = [
        data
        for data in month_list
        if data["product"] == pid and data["trade_year"] == year
    ]

    month_list_data_month = [data["trade_month"] for data in month_list_data]
    month_list_data_sales = [data["total_sales"] for data in month_list_data]

    # ==========================================================================
    # 상품 목록 보여주기(해당 년도만 보여주기)
    product_list = Trade_Total.objects.values("product", "trade_year")
    product_list_data = [
        data
        for data in product_list
        if data["trade_year"] == year and data["product"] != pid
    ]
    product_list_data_pid = set(data["product"] for data in product_list_data)

    products = Product.objects.filter(id__in=product_list_data_pid).values(
        "id", "brand", "name_kor", "model_no", "original_price", "product_detail_url"
    )

    # ==========================================================================
    # 원차트용 사이즈별 판매량
    total_sales_per_size = (
        Trade_Total.objects.values("product", "trade_year", "trade_size")
        .annotate(total_sales=Sum("trade_price"))
        .order_by("trade_size")
    )

    size_list = [
        data["trade_size"]
        for data in total_sales_per_size
        if data["trade_year"] == year and data["product"] == pid
    ]

    size_sales = [
        data["total_sales"]
        for data in total_sales_per_size
        if data["trade_year"] == year and data["product"] == pid
    ]

    # 워드 클라우드
    df = pd.read_excel(
        "C:\\source\\pythonsource\\kream_project\\clean_data\\trade_noun.xlsx"
    )

    product = get_object_or_404(Product, id=pid)

    model_no = product.model_no

    product_data = df[df["Model_No"] == model_no]

    words = product_data["Social_Text"].dropna().to_list()

    wordcloud_image = None

    if words:
        word_counts = Counter(" ".join(words).split())
        wordcloud_image = draw_wordclouds(word_counts)

    return render(
        request,
        "kream/detail.html",
        {
            "product_list": product_list,
            "single_product": single_product,
            "current_year": year,
            "total_sum_data": filtered_total_sum_data,
            "total_avg_data": filtered_total_avg_data,
            "year": year,
            "total_sum_data_curr_year": total_sum_data_curr_year,
            "total_sum_data_prev_year": total_sum_data_prev_year,
            "year_list_data": year_list_data,
            "month_list_data_month": month_list_data_month,
            "month_list_data_sales": month_list_data_sales,
            "products": products,
            "year_list": year_list,
            "pid": pid,
            "size_list": size_list,
            "size_sales": size_sales,
            "wordcloud_image": wordcloud_image,
        },
    )


@login_required(login_url="common:login")
def list(request):
    product_list = Product.objects.all()

    latest_year_per_product = Trade_Total.objects.values("product").annotate(
        max_year=Max("trade_year")
    )
    # <QuerySet [{'product': 1, 'max_year': 2024}, {'product': 2, 'max_year': 2024}, {'product': 3, 'max_year': 2024}]>

    return render(
        request,
        "kream/list.html",
        {
            "product_list": product_list,
            "latest_year_per_product": latest_year_per_product,
        },
    )


@login_required(login_url="common:login")
def home(request):
    # 전체 매출액
    # select sum(total_sales) from Trade group by product
    total_sales_per_product = Trade_Total.objects.values("product").annotate(
        total_sales=Sum("trade_price")
    )
    total_sales_sum = sum(item["total_sales"] for item in total_sales_per_product)

    # 년도마다 매출액 비교
    # select sum(total_sales) from Trade group by trade_year
    total_sales_per_year = Trade_Total.objects.values("trade_year").annotate(
        total_sales=Sum("trade_price")
    )

    # <QuerySet [{'trade_year': 2022, 'total_sales': 1176912}, {'trade_year': 2023, 'total_sales': 799145}, {'trade_year': 2024, 'total_sales': 2699080}]>
    # total_sales_per_year = total_sales_per_year[0].get("total_sales")

    total_sales_sum_per_year = [data["total_sales"] for data in total_sales_per_year]

    # 최신년도
    total_latest = total_sales_per_year[total_sales_per_year.__len__() - 1].get(
        "trade_year"
    )

    # 총 년도의 개수
    count_year = total_sales_per_year.__len__()

    # 최신 년도 값
    year = total_sales_per_year[total_sales_per_year.__len__() - 1].get("trade_year")
    # toLocaleString : 콤마 넣기 (자바스크립트) const formatValue = value.toLocaleString('ko-KR');

    # 월마다 총 매출액
    # select sum(total_sales) from Trade group by trade_month
    # <QuerySet [{'trade_year': 2022, 'trade_month': 3, 'total_sales': 45600}, {'trade_year': 2022, 'trade_month': 5, 'total_sales': 454545}]>
    total_sales_per_month = Trade_Total.objects.values(
        "trade_year", "trade_month"
    ).annotate(total_sales=Sum("trade_price"))

    # 최신 월의 값
    month = total_sales_per_month[total_sales_per_month.__len__() - 1].get(
        "trade_month"
    )

    # 각 년도마다 현재 최신 달
    latest_month_per_year = [
        data for data in total_sales_per_month if data["trade_month"] == month
    ]
    # [{'trade_year': 2023, 'trade_month': 8, 'total_sales': 453}, {'trade_year': 2024, 'trade_month': 8, 'total_sales': 1317098}]

    latest_month_per_year_data = [data["total_sales"] for data in latest_month_per_year]

    # trade_year가 가장 최신년도인 항목만 필터링
    latest_year_data = [
        data for data in total_sales_per_month if data["trade_year"] == total_latest
    ]

    # 최신 년도의 거래된 월들
    latest_year_months = [data["trade_month"] for data in latest_year_data]

    # 월들의 개수
    count_month = latest_year_months.__len__()

    # 최신 년도의 거래된 월마다의 총 매출액
    latest_year_months_data = [data["total_sales"] for data in latest_year_data]

    # 현재 월을 이용하여 현재 분기 계산
    if month in [1, 2, 3]:
        current_quarter = 1
    elif month in [4, 5, 6]:
        current_quarter = 2
    elif month in [7, 8, 9]:
        current_quarter = 3
    elif month in [10, 11, 12]:
        current_quarter = 4

    # 분기별 그룹화
    quarter_group = (
        Trade_Total.objects.annotate(
            quarter=Case(
                When(trade_month__in=[1, 2, 3], then=1),
                When(trade_month__in=[4, 5, 6], then=2),
                When(trade_month__in=[7, 8, 9], then=3),
                When(trade_month__in=[10, 11, 12], then=4),
                output_field=IntegerField(),
            )
        )
        .values("quarter", "trade_year")
        .annotate(total_sales=Sum("trade_price"))
    )

    # 최신년도 현재분기 총매출액

django/kream/templates/kream/checkListDetail.html
{% extends "base.html" %}
{% block content %}
  {% load static %}

  <body class="nav-fixed bg-light">
    <!-- Top app bar navigation menu-->
    {% include "header.html" %}
    <!-- Layout wrapper-->
    <div id="layoutDrawer">
      <!-- Layout navigation-->
      <div id="layoutDrawer_nav">
        <!-- Drawer navigation-->
        {% include "sidebar.html" %}
      </div>
      <!-- Layout content-->
      <div id="layoutDrawer_content">
        <!-- Main page content-->
        <main>
          <!-- Page header-->
          <header class="bg-primary">
            <div class="container-xl p-5">
              <div class="row align-items-center justify-content-between">
                <div class="col-12 col-md mb-4 mb-md-0">
                  <h1 class="mb-1 display-4 fw-500 text-white">체크리스트</h1>
                  <p class="lead mb-0 text-white">할일을 기록해보세요</p>
                </div>
                <div class="col-12 col-md-auto flex-shrink-0">
                  {% comment %} <label class="form-label text-white-50" for="litepickerDateRange">Date range:</label> {% endcomment %}
                  {% comment %} <input class="form-control mb-0" id="litepickerDateRange" placeholder="Select date range..." value="Mar 8, 2023 - Mar 14, 2023" style="min-width: 13rem; height: 3rem"/> {% endcomment %}
                </div>
              </div>
            </div>
          </header>
          <div class="container-xl p-5">     
            <div class="row">
              <div class="mb-3">
                <label for="title" class="form-label">제목</label>
                <input type="text" class="form-control" id="title" name="title" value="{{record.title}}" readonly/>
              </div>
              <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" id="content" rows="9" name="content" readonly>{{record.content}}</textarea>
              </div>
              <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" value="True" id="important" name="important" {% if record.is_completed %} checked="checked{% endif %}"/>
                <label class="form-check-label" for="important">완료여부</label>
              </div>       
              <div>
                <a href="{% url "kream:modify" record.id %}" class="btn btn-primary">수정</a>
                {% comment %} <a href="{% url "kream:delete" record.id %}" class="btn btn-danger">삭제</a> {% endcomment %}
                <a href="{% url "kream:checkList" %}" class="btn btn-success">목록</a>
              </div>
            </div>         
          </div>
        </main>
        
        {% include "footer.html" %}
      </div>
    </div>
    <form action="{% url "common:logout" %}" method="post" id="logoutForm">
      {% csrf_token %}
    </form>
    <!-- Load Bootstrap JS bundle-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <!-- Load global scripts-->
    <script type="module" src="{% static "js/material.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="{% static "js/base.js" %}"></script>
    <script src="{% static "js/list.js" %}"></script>
    <!-- Load Simple DataTables Scripts-->
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="{% static "js/datatables/datatables-simple-demo.js" %}"></script>
    <!-- Load Litepicker plugin scripts-->
    <script src="https://cdn.jsdelivr.net/npm/litepicker/dist/js/main.nocss.js" crossorigin="anonymous"></script>
    {% comment %} <script src="{% static "js/litepicker.js" %}"></script> {% endcomment %}
  </body>
{% endblock content %}

django/kream/templates/kream/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <body class="nav-fixed bg-light">
    
    {% include "header.html" %}
    <div id="layoutDrawer">
      <div id="layoutDrawer_nav">
        {% include "sidebar.html" %}
      </div>
      <div id="layoutDrawer_content">    
        <main>
          <div class="container-xl p-5">
            <div class="row justify-content-between align-items-center mb-3">
              <div class="col flex-shrink-0 mb-3 mb-md-0">
                <h1 class="display-4 mb-0">상품 상세분석</h1>
                <input type="hidden" name="" value="{{single_product.id}}" id="pid">
                <div class="text-muted"></div>
              </div>  
              <div class="col-12 col-md-auto" id="selectParent">
                <div class="d-flex flex-column flex-sm-row gap-3 align-items-center">
                  <div>년도 선택</div>
                  <select class="form-select" aria-label="Default select example" id="select" placeholder="년도선택">
                    {% for y in year_list_data %}
                      <option value="{{y}}" {% if year == y %}selected{% endif %} id="option">{{y}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>  
            <div class="row gx-5">
              <div class="col-xxl-3 col-md-6 mb-5">
                <div class="card card-raised border-start border-primary border-4 w-78">
                  <div class="card-body px-4">
                    <div class="d-flex align-items-center">
                      <div class="me-4">
                        <div class="display-5">PDF 저장</div>
                        <div class="card-text"></div>
                      </div>
                      <button id="savePdfButton" class="btn btn-primary ms-2">
                        <i class="material-icons">download</i>
                      </button>
                    </div>
                  </div>
                </div>
              </div>   
            </div>   
            <div id="chartContainer">
              <div class="row gx-5">
                <div class="col-lg-8 mb-5">
                  <div class="card card-raised h-100">
                    <div class="card-header bg-primary text-white px-4">
                      <div class="d-flex justify-content-between align-items-center">
                        <div class="me-4">
                          <img src="{{single_product.img_url}}" class="img-thumbnail" alt="...">                      
                        </div>
                        <div class="text-center w-100">                    
                        <h2 class="text-white">{{single_product.name_kor}}</h2>
                        <h5 class="text-white">{{single_product.model_no}}</h5>
                      </div> 
                      </div>
                    </div>
                    <div class="card-body p-4">
                      <div class="row gx-4">
                        <div class="col-12 col-xxl-2">
                          <div class="d-flex flex-column flex-md-row flex-xxl-column align-items-center align-items-xl-start justify-content-between">
                            <div class="mb-4 text-center text-md-start">
                              <div class="text-xl font-monospace text-muted mb-1">총 판매금액</div>
                              <div class="display-6 fw-400" id="totalSale">{{total_sum_data}}</div>                            
                            </div>
                            <div class="mb-4 text-center text-md-start">
                              <div class="text-xl font-monospace text-muted mb-1">평균 판매금액</div>
                              <div class="display-6 fw-400" id="avgSale">{{total_avg_data}}</div>
                            </div>
                            <div class="mb-4 text-center text-md-start">
                              <div class="text-xl font-monospace text-muted mb-1" id="increaseText">지난해 대비 판매금액 증감비율</div>
                              <div class="display-6 fw-400 text-success" id="increase"></div>
                            </div>
                          </div>
                        </div>
                        <div class="col-12 col-xxl-10">                       
                            <canvas id="dashboardBarChart"></canvas>                        
                        </div>
                      </div>
                    </div>
                    <div class="card-footer bg-transparent position-relative ripple-gray">
                      <a class="d-flex align-items-center justify-content-end text-decoration-none stretched-link text-primary" href="{% url "kream:predictSales" pid %}">
                          <div class="fst-button">추후 매출액 예상</div>
                          <i class="material-icons icon-sm ms-1">chevron_right</i>
                      </a>
                    </div>
                  </div>
                </div>       
                <div class="col-lg-4 mb-5">
                  <div class="card card-raised h-100">
                    <div class="card-header bg-primary text-white px-4">
                      <div class="d-flex justify-content-between align-items-center">
                        <div class="me-4">
                          <h2 class="card-title text-white mb-0">사이즈별 총 매출액</h2>                       
                        </div>
                        <div class="dropdown">
                        </div>
                      </div>
                    </div>
                    <div class="card-body p-4">
                      <div class="d-flex h-100 w-100 align-items-center justify-content-center">
                        <div class="w-100" style="max-width: 20rem">
                          <canvas id="myPieChart"></canvas>
                        </div>
                      </div>
                    </div>
                    <div class="card-footer bg-transparent position-relative ripple-gray">
                      <a class="d-flex align-items-center justify-content-end text-decoration-none stretched-link text-primary" href="{% url "kream:sizeReport" pid %}">
                          <div class="fst-button">사이즈별 상세 리포트</div>
                          <i class="material-icons icon-sm ms-1">chevron_right</i>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card card-raised mb-4">
                <div class="card-header bg-primary text-white px-4">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                      <h2 class="card-title text-white mb-0">리뷰 키워드 워드클라우드</h2>
                      <div class="card-subtitle">상세정보</div>
                    </div>
                  </div>
                </div>
                <div class="card-body p-4">
                  <div class="wordcloud-container" >
                    <img src="data:image/png;base64,{{ wordcloud_image }}" alt="Word Cloud" id="wordcloudImg" >
                    <div id="noneMsg"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row gx-5">
              <div class="col-xl-6 mb-5">
                <div class="card card-raised h-100">
                  <div class="card-body p-4">
                    <div class="d-flex justify-content-between">
                      <img src="https://play-lh.googleusercontent.com/Gh73JjkOE27zN6F8l4tWqlzgpHMEyEZJLOOg8-RQfYtPBAwsSCWNcqvdhgTaqGSOLA" alt="..." style="height: 6rem; margin-right: 1rem;"/>
                      <div class="me-4">
                        <h2 class="card-title mb-0">Kream</h2>
                        <p class="card-text">크림 — 한정판 스니커즈부터 명품, 가전, 테크, 음반, 트레이딩 카드 까지! KREAM에서 바로 구매! 100% 정품 kream. 한정판을 구매하는 가장 안전한 방법! 웰컴드로우. 브랜드관 입점</p>
                      </div>  
                    </div>
                  </div>
                  <div class="card-footer bg-transparent position-relative ripple-gray px-4">
                    <a class="stretched-link text-decoration-none" href="https://kream.co.kr/search">https://kream.co.kr/search</a>
                  </div>
                </div>
              </div>
              <div class="col-xl-6 mb-5">
                <div class="card card-raised h-100">
                  <div class="card-body p-4">
                    <div class="d-flex justify-content-between">
                      <img src="https://play-lh.googleusercontent.com/cFdSDY1ilmENPoGhAYbNbx5sfmvDBz9MOP5-hTywWFfvp_y7k9ETj9Y3XwwOuLDTNIgU=s48-rw" alt="..." style="height: 6rem; margin-right: 1rem;"/>
                      <div class="me-4">
                        <h2 class="card-title mb-0">솔드아웃</h2>
                        <p class="card-text">믿을 수 있는 한정판 플랫폼, 갖고 싶은 한정판 다 솔드아웃에서</p>
                      </div>  
                    </div>
                  </div>
                  <div class="card-footer bg-transparent position-relative ripple-gray px-4">
                    <a class="stretched-link text-decoration-none" href="https://www.soldout.co.kr/search/product/list">https://www.soldout.co.kr/search/product/list</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="card card-raised">
              <div class="card-header bg-primary text-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="me-4">
                    <h2 class="card-title text-white mb-0">해당 년도 상품 목록</h2>
                    <div class="card-subtitle">상세정보</div>
                  </div> 
                </div>
              </div>
              <div class="card-body p-4">
                <table id="datatablesSimple">
                  <thead>
                    <tr>
                      <th>브랜드</th>
                      <th>이름</th>
                      <th>모델번호</th>
                      <th>가격</th>
                      <th>상품 상세페이지</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% comment %} 반복 영역 {% endcomment %}
                    {% for product in products %}
                        <tr id="productDetail">
                          <td>{{product.brand}}</td>
                          <td><a href="{% url "kream:detail" product.id year %}">{{product.name_kor}}</a></td>
                          <td>{{product.model_no}}</td>
                          <td>{{product.original_price}}원</td>
                          <td><a href="{{product.product_detail_url}}">{{product.product_detail_url}}</a></td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </main>
        {% include "footer.html" %}
      </div>
    </div>
    <form action="{% url "common:logout" %}" method="post" id="logoutForm">
      {% csrf_token %}
    </form>
    
    {% comment %} js로 사용하기 위한 데이터 {% endcomment %}
    <input type="hidden" value="{{pid}}" name="" id="productId">
    <input type="hidden" data-curr="{{total_sum_data_curr_year}}" data-prev="{{total_sum_data_prev_year}}" name="" value="{{year}}" id="increaseCal">
    <input type="hidden" name="" value="{{year_list_data}}" id="yearList">
    <input type="hidden" name="" data-month="{{month_list_data_month}}" data-sales="{{month_list_data_sales}}" id="monthList">
    <input type="hidden" name="" data-sizeList="{{size_list}}" data-sales="{{size_sales}}" id="sizeChart">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static "js/material.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.0.2/chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static "js/charts/chart-defaults.js" %}"></script>
    <script src="{% static "js/charts/demos/chart-pie-demo.js" %}"></script>
    <script src="{% static "js/charts/demos/dashboard-chart-bar-grouped-demo.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="{% static "js/datatables/datatables-simple-demo.js" %}"></script>
    <script src="{% static "js/base.js" %}"></script>
    <script src="{% static "js/detail.js" %}"></script>
    <script src="{% static "js/digit.js" %}"></script>
    <script src="{% static "js/wordcloud.js" %}"></script>
    <script src="{% static "js/html2canvas.js" %}"></script>
    <script src="{% static "js/jspdf.min.js" %}"></script>
    <script src="{% static "js/pdf2.js" %}"></script>
    
    {% block script %}{% endblock script %}
  </body>
  {% endblock content %}