django/blog/blog/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.list, name="list"),
    path("post/<int:post_id>/", views.detail, name="detail"),
    path("post/create/", views.create, name="create"),
    path("post/modify/<int:post_id>/", views.modify, name="modify"),
    path("post/delete/<int:post_id>/", views.delete, name="delete"),
    # ===========================================================
    # 댓글
    path("post/comment/<int:post_id>/", views.comment_create, name="comment_create"),
    # 좋아요
    path("post/like/<int:post_id>/", views.post_like, name="post_like"),
]

django/blog/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", RedirectView.as_view(url="/blog/"), name="index"),
    path("common/", include("common.urls")),
]

# 파일 업로드 URL 환경설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to="image")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    likes = models.ManyToManyField(User, related_name="likes", blank=True)

    # list 추출 시 처음부터 작성일자 내림차순으로 정렬
    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return "%s - %s" % (self.id, self.user)

django/blog/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        # fields = "__all__"
        fields = ["title", "content", "image", "tags"]

django/blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Post, Comment
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse


# Create your views here.
def list(request):
    page = request.GET.get("page", 1)
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 5)
    page_obj = paginator.get_page(page)
    return render(request, "blog/list.html", {"post_list": page_obj})


def detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # 로그인 유저가 해당 게시물에 좋아요 했는지 여부
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    return render(request, "blog/post.html", {"post": post, "is_liked": is_liked})


@login_required(login_url="common:login")
def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # 태그 저장
            form.save_m2m()
            return redirect("blog:list")
    else:
        form = PostForm()

    return render(request, "blog/create.html", {"form": form})


@login_required(login_url="common:login")
def modify(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("blog:detail", post.id)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/modify.html", {"form": form, "post": post})


def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect("blog:list")


def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        content = request.POST.get("content")
        comment = Comment.objects.create(user=request.user, post=post, content=content)
        comment.save()
        return redirect("blog:detail", post.id)

    return redirect("blog:detail", post.id)


def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # 로그인 유저가 해당 게시물에 좋아요 했는지 여부
    is_liked = post.likes.filter(id=request.user.id).exists()

    is_liked_change = False

    if is_liked:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        is_liked_change = True

    return JsonResponse({"likes": post.likes.count(), "is_liked": is_liked_change})

django/blog/templates/blog/create.html
{% extends "base.html" %}
{% block content %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% comment %} 파일 들어가면 enctype="multipart/form-data" 설정 {% endcomment %}
                {% include "form_errors.html" %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="title">제목</label>
                        <input type="text" name="title" id="title" class="form-control" value="{{form.title.value|default_if_none:''}}"/>
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for=" content">내용</label>
                        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for="image">이미지</label>
                        <input type="file" name="image" id="image" class="form-control">
                    </div>

                    <div class="form-group mb-3">
                        <label for="tags">태그</label>
                        <input type="text" name="tags" id="tags" class="form-control" value="{{form.tags.value|default_if_none:''}}"/>
                        <small>태그는 콤마로 구분해서 입력하세요</small>
                    </div>
                    <input type="submit" value="새글 등록" class="btn btn-primary"/>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

django/blog/templates/blog/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div>
          <a href="{% url "blog:create" %}" class="btn btn-danger">새글작성</a>
        </div>
        <!-- Post preview-->
        {% for post in post_list %}
        <div class="post-preview">
          <a href="{% url "blog:detail" post.id %}">
            <h2 class="post-title">
              {{post.title}}
            </h2>
            
            <h3 class="post-subtitle">
              {{post.content | truncatechars:100}}
            </h3>
          </a>
          <p class="post-meta">
            Posted by
            <a href="#!">
              {{post.user}}
            </a>     
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <!-- Post preview-->
        <div class="post-preview">
          <a href="post.html"
            ><h2 class="post-title"></h2></a
          >
          <p class="post-meta">
            Posted by
            <a href="#!">{{post.created_at}}</a>  
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- Post preview-->
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">Science has not yet mastered prophecy</h2>
            <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the next ten.</h3>
          </a>
          <p class="post-meta">
            Posted by
            <a href="#!">Start Bootstrap</a>
            on August 24, 2023
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <!-- Post preview-->
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">Failure is not an option</h2>
            <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to future generations.</h3>
          </a>
          <p class="post-meta">
            Posted by
            <a href="#!">Start Bootstrap</a>
            on July 8, 2023
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        <!-- Pager-->
        <div class="d-flex justify-content-center mb-4">
          {% if post_list.has_previous %}
            <a class="btn btn-primary text-uppercase" href="?page={{post_list.previous_page_number}}">← Previous Posts</a>
          {% endif %}

          <a class="btn btn-primary text-uppercase" href="#">{{post_list.number}}/{{post_list.paginator.num_pages}}</a>

          {% if post_list.has_next %}
            <a class="btn btn-primary text-uppercase" href="?page={{post_list.next_page_number}}">Next Posts →</a>
          {% endif %}
        </div>
        
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/modify.html
{% extends "base.html" %}
{% block content %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% comment %} 파일 들어가면 enctype="multipart/form-data" 설정 {% endcomment %}
                {% include "form_errors.html" %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="title">제목</label>
                        <input type="text" name="title" id="title" class="form-control" value="{{form.title.value|default_if_none:''}}"/>
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for=" content">내용</label>
                        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for="image">이미지</label>                        
                    </div>
                    {% if form.image.value %}
                    <div class="row mb-2">
                        <div class="col-auto">현재</div>
                        <div class="col-auto">
                            <a href="{{form.image.value.url}}"><span>{{form.image.value.name}}</span></a>
                        </div>
                        <div class="col-auto">
                            {% comment %} name="image-clear" 체크하면 삭제해줌 {% endcomment %}
                            <input type="checkbox" name="image-clear" id="image-clear_id" class="form-check-input">
                            <label for="image-clear-id" class="form-check-label">취소</label>                        
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group mb-2">
                        변경
                        <input type="file" name="image" id="image" class="form-control">
                    </div>

                    <div class="form-group mb-2">
                        <input type="submit" value="수정" class="btn btn-primary"/>
                        <a href="{% url "blog:delete" post.id %}" class="btn btn-danger">삭제</a>
                        <a href="{% url "blog:list" %}" class="btn btn-info">목록</a>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

django/blog/templates/blog/post.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/post.css" %}">
{% endblock css %}
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="row">
                        <div class="col-md-10">
                            <h3 class="border-bottom pb-2">
                                {% comment %} 제목 {% endcomment %}
                                {{post.title}}
                            </h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <h3 class="border-bottom pb-2">
                                {% comment %} 이미지 {% endcomment %}
                                {% if post.image %}
                                    <img src="{{post.image.url}}" alt="" class="mx-auto d-block">
                                {% endif %}
                            </h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <h3 class="border-bottom pb-2">
                                {% comment %} 본문 {% endcomment %}
                                <p>
                                    {{post.content}}
                                </p>
                            </h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <h3 class="border-bottom pb-2">
                                <a href="{% url "blog:modify" post.id %}" class="btn btn-info">수정</a>
                                <a href="{% url "blog:list" %}" class="btn btn-success">목록</a>
                            </h3>
                        </div>
                    </div>

                    {% include "like.html" %}

                    {% comment %} taggit {% endcomment %}
                    <div class="row mt-5">
                        <div class="col-md-10">
                            {% for tag in post.tags.all %}
                                <span class="badge rounded-pill text-bg-dark">#{{tag.name}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    {% comment %} 댓글 목록 처리 {% endcomment %}
                    {% if post.comment_set.count > 0 %}
                    <div class="row mt-5">
                        <div class="col-md-10">
                            <div class="card mb-5">
                                <div class="card-header">
                                    <i class="fa-regular fa-comments"></i>
                                    Comments
                                </div>
                                {% comment %} 댓글 반복 영역 {% endcomment %}
                                {% for comment in post.comment_set.all %}
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            {% comment %} 댓글 내용 {% endcomment %}
                                            {{comment.content}}
                                        </h5>
                                        <div class="card-text text-end fs-6 bg-light">
                                            {% comment %} 댓글 작성자(댓글 작성 일시) {% endcomment %}
                                            {{comment.user}}({{comment.created_at}})
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    {% comment %} 댓글 등록 {% endcomment %}
                    {% if user.is_authenticated %}
                    <div class="row mt-5">
                        <div class="col-md-10">
                            <form action="{% url "blog:comment_create" post.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <textarea name="content" id="content" class="form-control" row="10"></textarea>
                                </div>
                                <div class="form-group d-grid">
                                    <button type="submit" class="btn btn-secondary">댓글 등록</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>
{% endblock content %}
{% block script %}
    <script src="{% static "js/post.js" %}"></script>
{% endblock script %}