django/kream/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "common"

urlpatterns = [
    path("register/", views.register, name="register"),
    # login 처리를 하는 뷰가 함수형뷰가 아니라 클래스뷰임
    # 클래스뷰를 함수형처럼 사용하려면 as_view() 사용
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="common/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # 기존 비밀번호 변경 후 세션 값 다시 담아줌
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="common/password_change.html",
            success_url=reverse_lazy("index"),
        ),
        name="password_change",
    ),
    # 비밀번호 초기화
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="common/password_reset.html",
            email_template_name="common/password_reset_email.txt",
            success_url=reverse_lazy("common:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html",
            success_url=reverse_lazy("common:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="common/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

django/kream/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("kream/", include("kream.urls")),
    path("", RedirectView.as_view(url="/common/login/"), name="index"),
    path("common/", include("common.urls")),
]

django/kream/kream/urls.py
from django.urls import path
from . import views


app_name = "kream"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("detail/<int:pid>/<int:year>/", views.detail, name="detail"),
    path("list/", views.list, name="list"),
    path("monthList/", views.monthList, name="monthList"),
    path("monthly/<int:year>/<int:month>/", views.monthlyReport, name="monthlyReport"),
    path("checkList/", views.checkList, name="checkList"),
    path("checkListDetail/<int:cid>/", views.checkListDetail, name="checkListDetail"),
    path("checkListDetail/modify/<int:cid>/", views.modify, name="modify"),
    path("checkListDetail/delete/<int:cid>/", views.delete, name="delete"),
    path("checkListCreate/", views.create, name="create"),
    path("sizeReport/<int:pid>/", views.sizeReport, name="sizeReport"),
    path("predictSales/<int:pid>/", views.predictSales, name="predictSales"),
]

django/kream/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Dashboard - Material Admin Pro</title>
    <!-- Load Favicon-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static "assets/img/favicon.ico" %}" rel="shortcut icon" type="image/x-icon"/>
    <!-- Load Material Icons from Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet"/>
    <!-- Load Simple DataTables Stylesheet-->
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"/>
    <!-- Roboto and Roboto Mono fonts from Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500" rel="stylesheet"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Load main stylesheet-->
    <link href="{% static "css/styles.css" %}" rel="stylesheet"/>

    {% block css %}{% endblock css %}
  </head>

  <!-- Main Content-->
  {% block content %}{% endblock content %}

  {% block script %}{% endblock script %}

</html>

django/kream/templates/footer.html
<footer class="py-4 mt-auto border-top" style="min-height: 74px">
  <div class="container-xl px-5">
    <div class="d-flex flex-column flex-sm-row align-items-center justify-content-sm-between small">
      <div class="me-sm-2">한정판 거래 온라인 플랫폼 상품 데이터 분석 프로젝트</div>
      <div class="d-flex ms-sm-2">
        <a class="text-decoration-none" href="#!"></a>
        <div class="mx-1">&middot;</div>
        <a class="text-decoration-none" href="#!"></a>
      </div>
    </div>
  </div>
</footer>

django/kream/templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <!-- 필드 오류 출력:입력값 누락, 형식에 맞지 않는 경우 -->
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{error}}
      </div>
    {% endfor %}
  {% endfor %}
  <!-- 넌필드 오류 출력 : 입력값과 관계없이 발생한 오류 -->
  {% for error in field.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

django/kream/templates/header.html
<nav class="top-app-bar navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid px-4">
    <!-- Drawer toggle button-->
    <button class="btn btn-lg btn-icon order-1 order-lg-0" id="drawerToggle" href="javascript:void(0);">
      <i class="material-icons">menu</i>
    </button>
    <!-- Navbar brand-->
    <a class="navbar-brand me-auto" href="{% url "kream:home" %}">
      <div class="">한정판 거래 온라인 플랫폼 상품 데이터 분석</div>
    </a>
    <!-- Navbar items-->
    <div class="d-flex align-items-center mx-3 me-lg-0">
      <!-- Navbar buttons-->
      <div class="d-flex">

        <!-- User profile dropdown-->
        <div class="dropdown">
          <button class="btn btn-lg btn-icon dropdown-toggle" id="dropdownMenuProfile" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="material-icons">person</i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end mt-3" aria-labelledby="dropdownMenuProfile">
            {% if not user.is_authenticated %}
              <li>
                <a class="dropdown-item" href="{% url "common:login" %}">로그인</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url "common:register" %}">회원가입</a>
              </li>
            {% else %}
              <li>
                <a class="dropdown-item" href="#" id="logout">로그아웃</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url "common:password_change" %}" id="logout">비밀번호 변경</a>
              </li>

            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

django/kream/templates/sidebar.html
<nav class="drawer accordion drawer-light bg-white" id="drawerAccordion">
  <div class="drawer-menu">
    <div class="nav">

      <!-- Divider-->
      <div class="drawer-menu-divider d-sm-none"></div>
      <!-- Drawer section heading (Interface)-->
      <div class="drawer-menu-heading">메뉴</div>
      <!-- Drawer link (Overview)-->
      <a class="nav-link" href="{% url "kream:home" %}">
        <div class="nav-link-icon">
          <i class="material-icons">home</i>
        </div>
        홈
      </a>
      <!-- Drawer link (Dashboards)-->
      <a class="nav-link collapsed" href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapseDashboards" aria-expanded="false" aria-controls="collapseDashboards">
        <div class="nav-link-icon">
          <i class="material-icons">bar_chart</i>
        </div>
        상세목록
        <div class="drawer-collapse-arrow">
          <i class="material-icons">expand_more</i>
        </div>
      </a>
      <!-- Nested drawer nav (Dashboards)-->
      <div class="collapse" id="collapseDashboards" aria-labelledby="headingOne" data-bs-parent="#drawerAccordion">
        <nav class="drawer-menu-nested nav">
          <a class="nav-link" href="{% url "kream:list" %}">상품목록</a>
          <a class="nav-link" href="{% url "kream:monthList" %}">월별 목록</a>
          <a class="nav-link" href="{% url "kream:checkList" %}">체크리스트 목록</a>
        </nav>
      </div>

      <!-- Divider-->
      <div class="drawer-menu-divider"></div>
      <!-- Drawer section heading (Plugins)-->

      <!-- Drawer footer -->
      <div class="drawer-footer border-top">
        {% if user.is_authenticated %}
          <div class="d-flex align-items-center">
            <i class="material-icons text-muted">account_circle</i>
            <div class="ms-3">
              <div class="caption">Logged in as:</div>
              <div class="small fw-500">{{user.username}}</div>
            </div>
          </div>
        {% endif %}
      </div>
    </nav>