django/board/board/urls.py
from django.urls import path
from .views import base_views, question_views, vote_views, answer_views, comment_views

app_name = "board"

urlpatterns = [
    # http://localhost:8000/board/
    path("", base_views.question_list, name="question_list"),
    # http://localhost:8000/board/1
    path("<int:qid>/", base_views.question_detail, name="question_detail"),
    # http://localhost:8000/board/question/create
    path("question/create/", question_views.question_create, name="question_create"),
    # http://localhost:8000/board/answer/create/2 (질문번호)
    path("answer/create/<int:qid>/", answer_views.answer_create, name="answer_create"),
    # http://localhost:8000/board/question/modify/3
    path(
        "question/modify/<int:qid>/",
        question_views.question_modify,
        name="question_modify",
    ),
    # http://localhost:8000/board/question/delete/3
    path(
        "question/delete/<int:qid>/",
        question_views.question_delete,
        name="question_delete",
    ),
    # http://localhost:8000/board/answer/modify/3/2
    path("answer/modify/<int:aid>/", answer_views.answer_modify, name="answer_modify"),
    # http://localhost:8000/board/answer/delete/3/5
    path("answer/delete/<int:aid>/", answer_views.answer_delete, name="answer_delete"),
    # ---------------------------------------------------
    # question 댓글
    # http://localhost:8000/board/comment/create/question/1
    path(
        "comment/create/question/<int:qid>/",
        comment_views.comment_create_question,
        name="comment_create_question",
    ),
    # http://localhost:8000/board/comment/modify/question/1
    path(
        "comment/modify/question/<int:cid>/",
        comment_views.comment_modify_question,
        name="comment_modify_question",
    ),
    # http://localhost:8000/board/comment/delete/question/1
    path(
        "comment/delete/question/<int:cid>/",
        comment_views.comment_delete_question,
        name="comment_delete_question",
    ),
    # ---------------------------------------------------
    # answer 댓글
    # http://localhost:8000/board/comment/create/answer/1
    path(
        "comment/create/answer/<int:aid>/",
        comment_views.comment_create_answer,
        name="comment_create_answer",
    ),
    # http://localhost:8000/board/comment/modify/answer/1
    path(
        "comment/modify/answer/<int:cid>/",
        comment_views.comment_modify_answer,
        name="comment_modify_answer",
    ),
    # http://localhost:8000/board/comment/delete/answer/1
    path(
        "comment/delete/answer/<int:cid>/",
        comment_views.comment_delete_answer,
        name="comment_delete_answer",
    ),
    # =-========================================================
    # 추천
    # http://localhost:8000/board/vote/question/qid
    path("vote/question/<int:qid>/", vote_views.vote_question, name="vote_question"),
    # http://localhost:8000/board/vote/answer/aid
    path("vote/answer/<int:aid>/", vote_views.vote_answer, name="vote_answer"),
]

django/board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("", RedirectView.as_view(url="/board/"), name="index"),
]

django/board/board/models.py
from django.db import models
from django.contrib.auth.models import User

# auto_now_add : 가장 처음 삽입시에만 날짜와 시간 삽입
# auto_now : 수정할 때마다 날짜와 시간 변경


class Question(models.Model):
    subject = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    # CASCADE : author 삭제 시 Question도 같이 삭제
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(null=True, blank=True, verbose_name="수정일시")

    # N:M 관계
    # User 입장에서 접근할수있는 컬럼이 2개...(voter, author) => 혼동 방지용으로 정확한 명칭을 부여
    voter = models.ManyToManyField(User, related_name="voter_question")

    view_cnt = models.BigIntegerField(default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(null=True, blank=True, verbose_name="수정일시")
    voter = models.ManyToManyField(User, related_name="voter_answer")

    def __str__(self):
        return self.content


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(null=True, blank=True, verbose_name="수정일시")

    # 댓글이 q댓글인지 a댓글인지 비어있을수있기때문에(q댓글이면 a댓글이 아님)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, null=True, blank=True
    )
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, blank=True)


class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unique__(self):
        return self.ip

django/board/board/forms.py
from .models import Question, Answer, Comment
from django import forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

django/board/board/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from board.models import Answer, Question
from board.forms import AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages


@login_required(login_url="common:login")
def answer_create(request, qid):
    """
    답변등록
    """
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            # return redirect("board:question_detail", qid=qid)
            # detail 페이지의 특정 위치 지정
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:question_detail", qid=qid), answer.id
                )
            )
    else:
        form = AnswerForm()

    # answer = Answer.objects.create(
    #     question=question, content=request.POST.get("content")
    # )

    # question.answer_set.create(content=request.POST.get("content"))

    # answer = Answer(question=question, content=request.POST.get("content"))
    # answer.save()

    # 실패 시 get 방식으로 처리
    context = {"question": question, "form": form}
    return render(request, "board/question_detail.html", context)


@login_required(login_url="common:login")
def answer_modify(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modified_at = timezone.now()
            answer.save()
            # return redirect("board:question_detail", qid=answer.question.id)
            # 수정 후 수정한 answer로 바로 가기
            return redirect(
                "{}#answer_{}".format(
                    resolve_url("board:question_detail", qid=answer.question.id),
                    answer.id,
                )
            )

    else:
        form = AnswerForm(instance=answer)

    return render(request, "board/answer_form.html", {"form": form})


@login_required(login_url="common:login")
def answer_delete(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    answer.delete()
    qid = answer.question.id
    return redirect("board:question_detail", qid)

django/board/board/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from board.models import Question, QuestionCount
from django.core.paginator import Paginator
from django.db.models import Q, Count  # or 조건으로 데이터 조회
from tools.utils import get_client_ip


def question_list(request):
    """전체 질문 추출"""

    # 현재 페이지 번호 가져오기
    page = request.GET.get("page", 1)

    # 검색어
    keyword = request.GET.get("keyword", "")

    # 정렬기준
    so = request.GET.get("so", "recent")

    # question_list = Question.objects.all()
    # question_list = Question.objects.order_by("-created_at")

    if so == "recommend":
        # 테이블에 num_voter 이름으로 임시 컬럼 생성
        question_list = Question.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-created_at"
        )
    elif so == "popular":  # 답변수
        question_list = Question.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-created_at"
        )
    else:
        question_list = Question.objects.order_by("-created_at")

    if keyword:
        question_list = question_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            # username : User객체의 아이디
            | Q(author__username__icontains=keyword)
            | Q(answer__author__username__icontains=keyword)
        ).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_list.html", context)


def question_detail(request, qid):
    question = get_object_or_404(Question, id=qid)
    # 클라이언트 ip 가져오기
    ip = get_client_ip(request)
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        # QuestionCount 객체 생성 후 저장
        qc = QuestionCount(ip=ip, question=question)
        qc.save()
        # Question의 view_cnt +1 추가
        if question.view_cnt > 0:
            question.view_cnt += 1
        else:
            question.view_cnt = 1
        question.save()

    # 현재 페이지 번호 가져오기
    page = request.GET.get("page", 1)

    # 검색어
    keyword = request.GET.get("keyword", "")

    # 정렬기준
    so = request.GET.get("so", "recent")

    context = {"question": question, "page": page, "keyword": keyword, "so": so}
    return render(request, "board/question_detail.html", context)

django/board/board/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from django.contrib import messages

from django.db.models import Q, Count  # or 조건으로 데이터 조회


@login_required(login_url="common:login")
def comment_create_question(request, qid):
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.question = question
            comment.save()
            # return redirect("board:question_detail", qid)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", qid),
                    comment.id,
                )
            )
    else:
        form = CommentForm()

    return render(
        request,
        "board/comment_form.html",
        {"form": form},
    )


@login_required(login_url="common:login")
def comment_modify_question(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:question_detail", comment.question.id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", comment.question.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_delete_question(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    comment.delete()
    return redirect("board:question_detail", comment.question.id)


@login_required(login_url="common:login")
def comment_create_answer(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.save()
            # return redirect("board:question_detail", aid)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", aid),
                    comment.id,
                )
            )
    else:
        form = CommentForm()

    return render(
        request,
        "board/comment_form.html",
        {"form": form},
    )


@login_required(login_url="common:login")
def comment_modify_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            # return redirect("board:question_detail", comment.answer.question.id)
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:question_detail", comment.answer.question.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


@login_required(login_url="common:login")
def comment_delete_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    comment.delete()
    return redirect("board:question_detail", comment.answer.question.id)

django/board/board/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from board.models import Question
from board.forms import QuestionForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages


@login_required(login_url="common:login")
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            # author ==> 현재 login한 사람
            question.author = request.user
            question.save()
            return redirect("board:question_list")
    else:
        form = QuestionForm()
    return render(request, "board/question_form.html", {"form": form})


@login_required(login_url="common:login")
def question_modify(request, qid):
    question = get_object_or_404(Question, id=qid)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modified_at = timezone.now()
            question.save()
            return redirect("board:question_detail", qid=qid)
    else:
        form = QuestionForm(instance=question)

    return render(request, "board/question_form.html", {"form": form})


@login_required(login_url="common:login")
def question_delete(request, qid):
    question = get_object_or_404(Question, id=qid)
    question.delete()
    return redirect("board:question_list")

django/board/board/views/vote_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from django.contrib import messages

from django.db.models import Q, Count  # or 조건으로 데이터 조회


@login_required(login_url="common:login")
def vote_question(request, qid):
    question = get_object_or_404(Question, id=qid)

    # 내가 작성한 글은 내가 추천 못함
    if question.author == request.user:
        # spring에서 log찍는거랑 비슷
        messages.error(request, "본인이 작성한 글은 추천이 불가능합니다")
    else:
        # 누가 작성했는지 정보 전달
        # add 함수에서 한번 누르면 또 못 올라가게 자동으로 해줌
        question.voter.add(request.user)

    return redirect("board:question_detail", qid)


@login_required(login_url="common:login")
def vote_answer(request, aid):
    answer = get_object_or_404(Answer, id=aid)

    # 내가 작성한 글은 내가 추천 못함
    if answer.author == request.user:
        # spring에서 log찍는거랑 비슷
        messages.error(request, "본인이 작성한 글은 추천이 불가능합니다")
    else:
        # 누가 작성했는지 정보 전달
        answer.voter.add(request.user)

    return redirect("board:question_detail", answer.question.id)

django/board/templates/board/answer_form.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">답변등록</h5>
    <form action="" method="post" class="my-3">
      {% include "form_errors.html" %}
      <!-- csrf token-->
      {% csrf_token %}
      <!-- 오류 표시 영역-->
      <div class="form-group mb-3">
        <label for=" subject">내용</label>
        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
      </div>
      <input type="submit" value="답변 등록" class="btn btn-primary"/>
    </form>
  </div>
{% endblock content %}

django/board/templates/board/comment_form.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">댓글등록</h5>
    <form action="" method="post" class="my-3">
      {% include "form_errors.html" %}
      <!-- csrf token-->
      {% csrf_token %}
      <!-- 오류 표시 영역-->
      <div class="form-group mb-3">
        <label for=" subject">내용</label>
        <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
      </div>
      <input type="submit" value="댓글 등록" class="btn btn-primary"/>
    </form>
  </div>
{% endblock content %}

django/board/templates/board/question_detail.html
{% extends "base.html" %}
{% block content %}
  {% load static %}

  <div class="container mt-5">
    {% if messages %}
    <div class="alert alert-danger">
      {% for msg in messages %}
      {% comment %} error(messages.error메소드 사용했기 때문) {% endcomment %}
        <strong>{{ msg.tags }}</strong>
        <ul>
          <li>{{msg.message}}</li>
        </ul>
        {% endfor %}
      </div>
    {% endif %}

    <h2 class="border-bottom py-2">
      <!-- 질문제목-->
      {{question.subject}}
    </h2>
    <!-- 추천 영역-->
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          <!--추천수-->
          {{question.voter.count}}
        </div>
        <div class="d-grid d-block">
          <a href="{% url "board:vote_question" question.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
        </div>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <!--질문내용-->
              {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
              {% if question.modified_at %}
                <div class="badge text-bg-light p-2 text-start">
                  <div class="mb-2">modified at</div>
                  <div>
                    <!--질문 수정 날짜-->
                    {{question.modified_at}}
                  </div>
                </div>
              {% endif %}
              <div class="badge text-bg-light p-2 text-start">
                <div class="mb-2">
                  <!--작성자-->
                  {{question.author}}
                </div>
                <div>
                  <!--질문 작성 날짜-->
                  {{question.created_at}}
                </div>
              </div>
            </div>
            {% comment %} 글 작성자 == 로그인 사용자 {% endcomment %}
            {% if question.author == request.user %}
              <div class="my-3">
                <a href="{% url "board:question_modify" question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="{% url "board:question_delete" question.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
              </div>
            {% endif %}
            <!--// 질문 영역 종료-->

            <!-- 질문 댓글 영역-->
             {% if question.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in question.comment_set.all %}
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line">{{comment.content}}</span>
                    <span>
                      <!--댓글 작성자 / 작성일시 / 수정일시-->
                      {{comment.author}}, {{comment.created_at}}, {{comment.modified_at|default_if_none:''}}
                    </span>
                    <a href="{% url "board:comment_modify_question" comment.id %}" class="small">수정</a>
                    <a href="{% url "board:comment_delete_question" comment.id %}" class="small delete">삭제</a>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="mx-3">
            <a href="{% url "board:comment_create_question" question.id %}" class="small">댓글추가....</a>
          </div>
        </div>
      </div>
    </div>

    <h5 class="border-bottom my-3 py-2">
      <!--답변 개수-->
      {{question.answer_set.count}}
      개의 답변이 있습니다.
    </h5>

    {% for answer in question.answer_set.all %}
    {% comment %} answer 수정 후 다시 돌아올 때 수정한 answer로 바로가게하기(answer마다 이름표 같은 느낌) {% endcomment %}
      <a name="answer_{{answer.id}}"></a>
      <div class="row my-3">
        <div class="col-1">
          <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
            {{answer.voter.count}}
          </div>
          <div class="d-grid d-block">
            <a href="{% url "board:vote_answer" answer.id %}" class="recommand btn btn-sm btn-secondary">추천</a>
          </div>
        </div>
        <div class="col-11">
          <div class="card">
            <div class="card-body">
              <div class="card-text" style="white-space: pre-line">
                <!--답변내용-->
                {{answer.content}}
              </div>
              <div class="d-flex justify-content-end">
                {% if answer.modified_at %}
                  <div class="badge text-bg-light p-2 text-start">
                    <div class="mb-2">modified_at</div>
                    <div>
                      <!--답변수정날짜-->
                      {{answer.modified_at}}
                    </div>
                  </div>
                {% endif %}
                <div class="badge text-bg-light p-2 text-start">
                  <div class="mb-2">
                    <!--답변 작성자-->
                    {{answer.author}}
                  </div>
                  <div>
                    <!--답변작성날짜-->
                    {{answer.created_at}}
                  </div>
                </div>
              </div>
              {% if answer.author == request.user %}
              <div class="my-3">
                <a href="{% url "board:answer_modify" answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="{% url "board:answer_delete" answer.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
              </div>
            {% endif %}
            </div>
            
            <!--// 답변 종료-->

            <!-- 답변 댓글 영역-->
             {% if answer.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in answer.comment_set.all  %}
                <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line">{{comment.content}}</span>
                    <span>
                      <!--댓글 작성자 / 작성일시 / 수정일시-->
                      {{comment.author}}, {{comment.created_at}}, {{comment.modified_at}}
                    </span>
                    <a href="{% url "board:comment_modify_answer" comment.id %}" class="small">수정</a>
                    <a href="{% url "board:comment_delete_answer" comment.id %}" class="small delete">삭제</a>
                  </div>
                {% endfor %}
              </div>              
              {% endif %}
              <a href="{% url "board:comment_create_answer" answer.id %}" class="small">
                <small>댓글추가...</small>
              </a>
            </div>
          </div>
        </div>
          <!--//질문 댓글 end-->
        </div>
      </div>
      <!-- 답변 한 개 영역 종료-->
    {% endfor %}
    <div>
      <a href="{% url "board:question_list" %}" class="btn btn-sm btn-primary" id="list">목록으로</a>
    </div>
    <form action="{% url "board:answer_create" question.id %}" method="post" class="my-3">
      <!-- csrf token-->
      {% csrf_token %}
      <!-- 오류 표시 영역-->
      {% include "form_errors.html" %}
      <div class="form-group mb-3">
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <input type="submit" value="답변 등록" class="btn btn-primary" {% if not user.is_authenticated %}disabled="disabled"{% endif %} />
    </form>
  </div>

  {% comment %} 목록으로 클릭 시 이동할 폼 {% endcomment %}
  <form action="" method="get" id="actionForm">
    <input type="hidden" name="keyword" value="{{keyword | default_if_none:''}}" id="keyword"/>
    <input type="hidden" name="page" value="{{page}}" id="page"/>
    <input type="hidden" name="so" value="{{so | default_if_none:''}}" id="so"/>
  </form>
{% endblock content %}

{% block script %}
  <script src="{% static "js/detail.js" %}"></script>
{% endblock script %}

django/board/templates/board/question_list.html
{% extends "base.html" %}
{% load board_filter %}
{% block content %}
  {% load static %}
  <div class="container">
    <div class="row mt-3 justify-content-between">
      <div class="col-md-3">
        <select class="form-select so">
          <option value="recent" {% if so == 'recent' %}selected='selected'{% endif %}>최신순</option>
          <option value="recommend" {% if so == 'recommend' %}selected='selected'{% endif %}>추천순</option>
          <option value="popular" {% if so == 'popular' %}selected='selected'{% endif %}>인기순</option>
        </select>
      </div>
      <div class="col-md-8">
        <div class="input-group mb-3">
          <input type="text" name="" id="top_keyword" class="form-control" value="{{keyword | default_if_none:''}}"/>
          <button class="btn btn-outline-secondary" type="submit" id="btn_search">찾기</button>
        </div>
      </div>
    </div>

    <div class="my-3">
      <table class="table">
        <thead>
          <tr class="table-succ-ess">
            <th scope="col">번호</th>
            <th scope="col">추천</th>
            <th scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일시</th>
            <th scope="col">조회수</th>
          </tr>
        </thead>
        <tbody>
          {% if question_list %}
            {% for question in question_list %}
              <tr>
                <th scope="row">
                  <!-- 번호 question_list.paginator.count : 전체게시물개수 question_list.start_index: 페이지당 시작되는 게시물의 시작 번호 12개 1 page : 12-3 2 page : 2 -->
                  {{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}
                </th>
                <td>
                  <span class="badge text-bg-warning px-2 py-1">
                    <!--질문 추천 수 보여주기-->
                    {{question.voter.count}}
                  </span>
                </td>
                <td>
                  <a href="{{question.id}}" class="text-decoration-none text-dark">
                    <!--질문 제목-->
                    {{question.subject}}

                    {% if question.answer_set.count > 0 %}
                      <span class="text-danger small mx-2">
                        <!-- 질문에 달린 답변의 개수 표시 -->
                        {{question.answer_set.count}}
                      </span>
                    {% endif %}
                  </a>
                </td>
                <td>
                  <!-- 질문 작성자 -->
                   {{question.author}}
                </td>
                <td>
                  <!-- 질문 작성일시 -->
                  {{question.created_at}}
                </td>
                <td>
                  {{question.view_cnt}}
                </td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="3">질문이 없습니다.</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
      <!-- 페이징 처리 -->
      <nav aria-label="">
        <ul class="pagination justify-content-center">
          {% if question_list.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{{question_list.previous_page_number}}">Previous</a>
            </li>
          {% endif %}

          {% for page in question_list.paginator.page_range %}
            {% if page >= question_list.number|add:-5 and page <= question_list.number|add:5%}
              <li class="page-item {% if page == question_list.number %}active{% endif %}">
                <a class="page-link" href="{{page}}">{{page}}</a>
              </li>
            {% endif %}
          {% endfor %}

          {% if question_list.has_next %}
            <li class="page-item">
              <a class="page-link" href="{{question_list.next_page_number}}">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>
      <div>
        <a href="{% url "board:question_create" %}" class="btn btn-primary">질문 등록</a>
      </div>
    </div>

    <!--페이지 번호 클릭 시 이동할 폼-->
    <form action="" method="get" id="actionForm">
      <input type="hidden" name="keyword" value="{{keyword | default_if_none:''}}" id="keyword"/>
      <input type="hidden" name="page" value="{{page}}" id="page"/>
      <input type="hidden" name="so" value="{{so | default_if_none:''}}" id="so"/>
    </form>
  </div>
{% endblock content %}
{% block script %}
  <script src="{% static "js/list.js" %}"></script>
{% endblock script %}